name: Build WLAN Pi image

on:
  # Allow manual runs of workflow from Actions tab
  workflow_dispatch:

  schedule:
    - cron: '37 5 * * *'
  push:
    branches:
      - force-build

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build image
        run: |
          last_commit_date=$(git log -1 --format=%cd --date=unix)
          last_day=$(date -d '-1 day' +%s)

          if [ "${last_commit_date}" -lt "${last_day}" ]; then
            echo "Nothig new to build."
            echo "Last commit:"
            git log -1 --format='%C(auto)%h (%cd) - %s' --date=relative
            exit 0
          fi

          sudo ./build-docker.sh

      - name: Archive image and upload to GitHub
        uses: actions/upload-artifact@v2
        with:
          name: wlanpi-image
          path: deploy/*.zip
